// [AVIS-AI-SCAN] FILE: mock_targets.h | CLASS: TEST_MOCKS | TARGET: WIN64_UCRT
#ifndef MOCK_TARGETS_H
#define MOCK_TARGETS_H

#include "cyborg_core.h"

#define VIRTUAL_CONSOLE_HANDLE  ((HWND)(ULONG_PTR)0xABCDE123)
#define VIRTUAL_SANDBOX_HANDLE  ((HWND)(ULONG_PTR)0x98765432)

#endif // MOCK_TARGETS_H
